services:
  neo4j:
    container_name: neo4j
    image: neo4j:2025.06.2
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always
    environment:
        - NEO4J_AUTH=neo4j/12345678
        - NEO4J_apoc_export_file_enabled=true
        - NEO4J_apoc_import_file_enabled=true
        - NEO4J_apoc_import_file_use_neo4j__config=true
        - NEO4J_PLUGINS=["apoc", "graph-data-science"]
    volumes:
        - ./neo4j_db/logs:/logs
        - ./neo4j_db/import:/var/lib/neo4j/import
        - ./neo4j_db/data:/data
        - ./neo4j_db/plugins:/plugins